### PR TITLE
INTLY-399 Fix incorrect links

### PR DESCRIPTION
**Pull request by aidenkeating**
Currently:
* Walkthrough 1A links to AMQ when it uses AMQ Online
* Walkthroughs have links that do not open in new tabs

## Verification
* Ensure that Walkthrough 1A right-hand side references AMQ Online and links to it.
* Ensure that all right-hand links open in a new tab and actually work.

Related to: https://github.com/integr8ly/tutorial-web-app/pull/356

### CODE REVIEW

**Comment by aidenkeating** [comment]
@finp @mfrances17 Would you mind taking a look? Not sure why the tests are failing, I'll look into it

**Comment by aidenkeating** [comment]
@david-martin Are we ok leaving this variable name as `enmasse-url` or should it be updated to `amq-online-url` before the release?

**Review by mfrances17 — APPROVED** [review]
Looks good. Just fix broken tests as you've already called out. Maybe just need to create a new snapshot?

**Comment by david-martin** [comment]
> Are we ok leaving this variable name as `enmasse-url` or should it be updated to `amq-online-url` before the release

I don't mind what it is, as the end user won't see it.
The important thing is that we don't have to keep changing it from here on, and it's correct in all places it's used

**Review by pwright — APPROVED** [review]

**Pull request merged**
