### PR TITLE
update walkthrough 2 with code ready

### PR DESCRIPTION
**Pull request by maleck13**
Moving to codeready GA

### CODE REVIEW

**Comment by maleck13** [comment]
@odra I have this deployed on my cluster. If you can use that to go through the api integration walkthroguh then I think we are good here

**Review by aidenkeating — APPROVED** [review]
One comment is that the diagram in the preamble still says `Eclipse Che`, I'm not sure where the source for that diagram is kept. Went through walkthrough 2 and it looks good though

**Comment by pwright** [comment]
@odra  I think you've updated that diagram?

**Comment by maleck13** [comment]
@aidenkeating updated to use @odra diagram

**Review by aidenkeating — APPROVED** [review]
Tried it out, diagram looks good

**Pull request merged**
