### PR TITLE
update docs for updating WALKTHROUGH_LOCATIONS

### PR DESCRIPTION
**Pull request by philbrookes**

### CODE REVIEW

**Review by pb82 — APPROVED** [review]
Verified on RHPDS, env var is updated

**Review by tremes — APPROVED** [review]
LGTM though the original way of changing the value was more user friendly IMO.

**Comment by pwright** [comment]
@tremes  I agree. I've updated the text since this merge, but i'm still not happy. For example, if a user wants to add a walkthrough repo for the first time, we don't provide a method for them to see what's currently 'published' to repo. I'd like to update the walkthrough to add that info (Before starting, check the env var), will ping you on that PR

**Comment by pwright** [comment]
@pb82  can we display the current value for WALKTHROUGH_LOCATIONS in a walkthrough? eg something like {webapp-WALKTHROUGH_LOCATIONS} ?

**Comment by pb82** [comment]
@finp Not at the moment, but we could expose this to walkthroughs if needed.

**Comment by pwright** [comment]
@pb82 That would be great. is there a pr i could copy to make this change, or should you do it?

**Comment by pb82** [comment]
@finp There is no PR i can think of, but i believe it would just be a matter of adding something like `'walkthrough-locations': process.env.WALKTHROUGH_LOCATIONS` here: https://github.com/integr8ly/tutorial-web-app/blob/master/src/common/docsHelpers.js#L20

**Pull request merged**
